# Site settings
name: HUANG CAIZHU
location: CHINA
company: UNIPD 
position: DATA SCIENCE
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: xxxx@xxx.com

baseurl: "/test"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

